tasks:
  - name: terraform
    before: |
      source ./bin/terraform/set_tf_alias
      source ./bin/terraform/install_terraform_cli
      source ./bin/terraform/generate_tfrc_credentials
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
     source ./bin/aws-use/login_ecr
     source ./bin/terraform/set_tf_alias
     source ./bin/aws-use/install_aws_cli

vscode:
  extensions:  
   - hashicorp.terraform  